version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/go:1.17
      - image: cimg/postgres:15.1
    steps:
      - checkout
      - run:
        name: install dependencies
        command: npm install
        
        'Codigo para correr pruebas'
      '- run:
        name: Run Tests
        command: npm run test'