version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/go:1.17
      - image: cimg/postgres:15.1.0
    steps:
      - checkout
      - run: --version